"""initial schema

Revision ID: 83223a41a984
Revises:
Create Date: 2026-09-17 13:53:05.316235
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "83223a41a984"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("name_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("whatsapp", sa.String(length=32), nullable=True),
        sa.Column(
            "whatsapp_status",
            sa.Enum(
                "not_found",
                "unconfirmed",
                "confirmed",
                name="whatsappstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "validation_status",
            sa.Enum(
                "unverified",
                "valid",
                "invalid",
                name="validationstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=150), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("category", sa.String(length=200), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("instagram", sa.String(length=200), nullable=True),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("confidence", sa.SmallInteger(), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 100)",
            name=op.f("ck_companies_confidence_range"),
        ),
        sa.CheckConstraint(
            "(whatsapp_status != 'confirmed' OR whatsapp IS NOT NULL) AND "
            "(whatsapp IS NULL OR whatsapp_status != 'not_found')",
            name=op.f("ck_companies_whatsapp_status_consistency"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_companies_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_companies_city"), ["city"], unique=False)
        batch_op.create_index(batch_op.f("ix_companies_cnpj"), ["cnpj"], unique=False)
        batch_op.create_index(
            "ix_companies_identity", ["name_fingerprint", "city", "state"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_companies_name_fingerprint"), ["name_fingerprint"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_companies_phone"), ["phone"], unique=False)
        batch_op.create_index(batch_op.f("ix_companies_state"), ["state"], unique=False)
        batch_op.create_index(batch_op.f("ix_companies_whatsapp"), ["whatsapp"], unique=False)

    op.create_table(
        "searches",
        sa.Column("original_query", sa.Text(), nullable=False),
        sa.Column("normalized_query", sa.Text(), nullable=False),
        sa.Column("query_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=200), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "running",
                "completed",
                "partial",
                "failed",
                "cancelled",
                name="searchstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "stage",
            sa.Enum(
                "created",
                "discovering",
                "enriching",
                "validating",
                "deduplicating",
                "finalizing",
                "completed",
                name="searchstage",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("results_count", sa.Integer(), nullable=False),
        sa.Column("whatsapp_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "results_count >= 0", name=op.f("ck_searches_results_count_non_negative")
        ),
        sa.CheckConstraint(
            "whatsapp_count >= 0", name=op.f("ck_searches_whatsapp_count_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_searches")),
    )
    with op.batch_alter_table("searches", schema=None) as batch_op:
        batch_op.create_index(
            "ix_searches_query_fingerprint_created_at",
            ["query_fingerprint", "created_at"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_searches_status"), ["status"], unique=False)

    op.create_table(
        "sources",
        sa.Column("provider_key", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=150), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "search",
                "directory",
                "registry",
                "website",
                "ai",
                "other",
                name="sourcetype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("provider_key", name=op.f("uq_sources_provider_key")),
    )
    op.create_table(
        "search_provider_runs",
        sa.Column("search_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "skipped",
                name="providerrunstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("results_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "results_count >= 0", name=op.f("ck_search_provider_runs_results_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["searches.id"],
            name=op.f("fk_search_provider_runs_search_id_searches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_search_provider_runs_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_provider_runs")),
        sa.UniqueConstraint("search_id", "source_id", name="search_source"),
    )
    with op.batch_alter_table("search_provider_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_search_provider_runs_search_id"), ["search_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_search_provider_runs_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "search_results",
        sa.Column("search_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.SmallInteger(), nullable=True),
        sa.Column("category_match", sa.Boolean(), nullable=True),
        sa.Column("qualification_reason", sa.Text(), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 100)",
            name=op.f("ck_search_results_confidence_range"),
        ),
        sa.CheckConstraint(
            "rank IS NULL OR rank > 0", name=op.f("ck_search_results_rank_positive")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_search_results_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["searches.id"],
            name=op.f("fk_search_results_search_id_searches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_results")),
        sa.UniqueConstraint("search_id", "company_id", name="search_company"),
    )
    with op.batch_alter_table("search_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_search_results_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_search_results_search_id"), ["search_id"], unique=False
        )

    op.create_table(
        "result_sources",
        sa.Column("search_result_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=300), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["search_result_id"],
            ["search_results.id"],
            name=op.f("fk_result_sources_search_result_id_search_results"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_result_sources_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_result_sources")),
    )
    with op.batch_alter_table("result_sources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_result_sources_search_result_id"), ["search_result_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_result_sources_source_id"), ["source_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("result_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_result_sources_source_id"))
        batch_op.drop_index(batch_op.f("ix_result_sources_search_result_id"))

    op.drop_table("result_sources")
    with op.batch_alter_table("search_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_results_search_id"))
        batch_op.drop_index(batch_op.f("ix_search_results_company_id"))

    op.drop_table("search_results")
    with op.batch_alter_table("search_provider_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_provider_runs_source_id"))
        batch_op.drop_index(batch_op.f("ix_search_provider_runs_search_id"))

    op.drop_table("search_provider_runs")
    op.drop_table("sources")
    with op.batch_alter_table("searches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_searches_status"))
        batch_op.drop_index("ix_searches_query_fingerprint_created_at")

    op.drop_table("searches")
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_companies_whatsapp"))
        batch_op.drop_index(batch_op.f("ix_companies_state"))
        batch_op.drop_index(batch_op.f("ix_companies_phone"))
        batch_op.drop_index(batch_op.f("ix_companies_name_fingerprint"))
        batch_op.drop_index("ix_companies_identity")
        batch_op.drop_index(batch_op.f("ix_companies_cnpj"))
        batch_op.drop_index(batch_op.f("ix_companies_city"))
        batch_op.drop_index(batch_op.f("ix_companies_category"))

    op.drop_table("companies")
    # ### end Alembic commands ###
